### PR TITLE
NO MRG, TST: Re-render with CircleCI matrix

### PR DESCRIPTION
**Pull request by jakirkham**
Please do **not** merge this PR. It is for testing purposes only.

Made changes to `conda-smithy` to try and support CircleCI 2.0's workflow format. In particular, this tries to use a matrix based on their parallel workflow. More details in the PR ( https://github.com/conda-forge/conda-smithy/pull/532 ).

### CODE REVIEW

**Comment by isuruf** [comment]
~There were 9 builds here, but only 4 statuses here~
There are 9. You have to scroll.

**Comment by jakirkham** [comment]
It requires scrolling to see. Might also be worth refreshing. FWIW I see 11 (9 from CircleCI, 1 from the linter, and 1 from Travis CI).

Admittedly how they display statuses here is my least favorite part, but I could get over that if we could avoid other hacks to achieve build matrices. 😉

**Comment by isuruf** [comment]
I wonder what would happen if there is a build step depending on all these 9 jobs. Maybe it'll show only one status.

**Comment by jakirkham** [comment]
I was wondering that too. Though have not yet tried. Also probably won't try now as it is late here. That said, would encourage you to if you are interested. 😉

Did try adding an initial step, which all other steps depended on. The result was the initial step also got tacked onto the status list with all the later steps. This makes me think the same would happen with a final unifying step, but I could be wrong (again haven't tried).

Also discovered that not as much info is shared between steps as one might like. Guessing the idea is to use the cache to handle this. Not sure if it is worth exploring that too much for our use case, but worth keeping in mind if one adds sequenced steps.

**Comment by gqmelo** [comment]
It is also weird that the builds are grouped under ```pull/null```: https://circleci.com/gh/conda-forge/rank_filter-feedstock/tree/pull%2Fnull

I wonder what would happen when there are two PR's

**Comment by jakirkham** [comment]
Good point. This doesn't seem to be unique to matrix builds FWICT, but is a CircleCI 2.0 issue. That said, the build number is unique to the repo build. It doesn't matter if it is a PR build or which branch on the main feedstock it came from. That number always increases. Still it is a UI issue that is worth noting and raising. So have done so.

ref: https://discuss.circleci.com/t/circleci-2-0-incorrectly-groups-pull/13505

**Comment by jakirkham** [comment]
> I wonder what would happen if there is a build step depending on all these 9 jobs. Maybe it'll show only one status.

As follow up on this, CircleCI includes a [fan-out fan-in example]( https://github.com/CircleCI-Public/circleci-demo-workflows/blob/fan-in-fan-out/.circleci/config.yml ), which still has [all status checks]( https://github.com/CircleCI-Public/circleci-demo-workflows/pull/4 ). So it seems that doesn't collapse the statuses to one.

**Comment by jakirkham** [comment]
Also raised a [discussion topic]( https://discuss.circleci.com/t/creating-one-github-status-for-workflow-of-multiple-jobs/14522 ) with CircleCI about getting a single GitHub status. Feel free to add more there if you would like and/or like the post.

**Comment by isuruf** [comment]
I guess this is okay once we move to single numpy build.

**Pull request closed without merging**
