### PR TITLE
Re-render with `conda-smithy` 0.9.2

### PR DESCRIPTION
**Pull request by jakirkham**
Re-renders the feedstock with `conda-smithy` version 0.9.2. This will give us support for NumPy 1.11.x.

### CODE REVIEW

**Comment by jakirkham** [comment]
Getting this out of here ASAP as it is a trivial re-rendering and need to get NumPy 1.11.x support ASAP.

**Comment by ocefpaf** [comment]
Are you doing those PRs by hand? I remember @pelson writing the instructions for the maintenance PRs   somewhere...

**Comment by jakirkham** [comment]
I'm using `conda smithy rerender` locally.

I haven't seen the instructions for sending PRs. Please feel free to direct me to them.

Though I think this is the last one that needs re-rendering for the moment. Trying to make sure I can get going with NumPy 1.11.x.

**Comment by ocefpaf** [comment]
The `...` was a sarcastic autocritique :wink: I do not recall and we should:
- [ ] add those instructions in a wiki
- [ ] try them out before we loose @pelson to the conference season/vacations

**Comment by jakirkham** [comment]
Yeah, honestly, I don't even know how to do this. I saw a few script commands that @pelson showed me, but this wasn't one of them.

I can show you how to unsubscribe from feedstocks that you are not listed as a maintainer on now. 😄

**Comment by jakirkham** [comment]
I'm guessing this is that [script](https://github.com/conda-forge/conda-forge.github.io/blob/a5da7a004e4af0340b3df556a2c78fa8e03c6689/scripts/regenerate_feedstock.py) though. 😉

**Comment by pelson** [comment]
> try them out before we loose @pelson to the conference season/vacations

Indeed :smile: - I may have a solution to this. I've pinged @jakirkham and we will iterate, then I'll fill you in @ocefpaf.

**Pull request merged**
