### PR TITLE
Try to add support for Windows

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/rank_filter-feedstock/issues/3

Attempts to add Windows support. Not sure if this is going to work or what will happen, but figure we should try to see.

### CODE REVIEW

**Comment by jakirkham** [comment]
Interesting. The linter didn't comment here. Are we overwhelming the linter in some way or is it being disabled intentionally somehow, @pelson?

**Comment by jakirkham** [comment]
Renamed the PR to convince the linter to comment. Seemed to work. We should investigate whether throttling or something else stopped this from working earlier.

**Comment by pelson** [comment]
It is possible to see the error by visiting this repo's setting on github -> webhooks, then looking at the conda-linter service on this repo.

In this case, it looks like there was a 500 internal server error raised. Looking at the heroku logs (using `heroku logs -n 3000` to see them all):

```
2016-05-17T19:43:39.602348+00:00 app[web.1]:   File "/app/conda_forge_webservices/webapp.py", line 61, in post
2016-05-17T19:43:39.602351+00:00 app[web.1]:     repo.remotes.origin.fetch('pull/{pr}/head:pr/{pr}'.format(pr=pr_id))
2016-05-17T19:43:39.602350+00:00 app[web.1]:   File "conda_forge_webservices/linting.py", line 31, in compute_lint_message
2016-05-17T19:43:39.602352+00:00 app[web.1]:     res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
2016-05-17T19:43:39.602351+00:00 app[web.1]:   File "/app/.conda/lib/python2.7/site-packages/git/remote.py", line 651, in fetch
2016-05-17T19:43:39.602354+00:00 app[web.1]:   File "/app/.conda/lib/python2.7/site-packages/git/remote.py", line 559, in _get_fetch_info_from_stderr
2016-05-17T19:43:39.602349+00:00 app[web.1]:     lint_info = linting.compute_lint_message(owner, repo_name, pr_id)
2016-05-17T19:43:39.602355+00:00 app[web.1]:     raise GitCommandError(("Error when fetching: %s" % line,), 2)
2016-05-17T19:43:39.602346+00:00 app[web.1]:   File "/app/.conda/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
2016-05-17T19:43:39.602355+00:00 app[web.1]: GitCommandError: 'Error when fetching: fatal: Couldn't find remote ref pull/4/head' returned with exit code 2
2016-05-17T19:43:39.602345+00:00 app[web.1]: Traceback (most recent call last):
2016-05-17T19:43:39.602994+00:00 app[web.1]: ERROR:tornado.access:500 POST /conda-linting/hook (192.30.252.42) 917.91ms
2016-05-17T19:43:39.602347+00:00 app[web.1]:     result = method(*self.path_args, **self.path_kwargs)
2016-05-17T19:43:39.601105+00:00 heroku[router]: at=info method=POST path="/conda-linting/hook" host=conda-forge.herokuapp.com request_id=7c6ee2f2-bf7e-4765-80de-9b3721ab8134 fwd="192.30.252.42" dyno=web.1 connect=0ms service=922ms status=500 bytes=255
```

**Comment by jakirkham** [comment]
Ah, thanks for the tip.

**Comment by pelson** [comment]
I have no idea _why_ it wasn't able to fetch that ref. Maybe it was requested quicker than github make it available or something?

**Comment by jakirkham** [comment]
Resolved in PR ( https://github.com/conda-forge/rank_filter-feedstock/pull/28 ).

**Pull request closed without merging**
